name: Run Rclone Docker Container

on:
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull and run Docker container
      run: |
        docker pull mirrorwithlove0/rclone
        docker run -d -p 6090:90 mirrorwithlove0/rclone

    - name: List running containers
      run: docker ps
